# Generated by Django 3.2.6 on 2021-08-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('text', models.CharField(max_length=2000)),
                ('create_date', models.DateField()),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
