# Generated by Django 3.2.6 on 2021-08-21 20:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=55)),
                ('Last_Name', models.CharField(max_length=55)),
                ('Department', models.CharField(max_length=55)),
                ('Salary', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateField(default=datetime.date.today)),
                ('createdby', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
