# Generated by Django 3.2.6 on 2021-08-18 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=55)),
                ('Last_Name', models.CharField(max_length=55)),
                ('Department', models.CharField(max_length=55)),
                ('Salary', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
